- name: Create portainer docker private network
  community.docker.docker_network:
    name: 'portainer-private-net'
    driver: overlay
    internal: true
    appends: true
    attachable: true
    state: present
  when: inventory_hostname == groups['managers'][0]

- name: Create docker volume for portainer
  community.docker.docker_volume:
    name: '{{ portainer_data_docker_volume }}'
    state: present
  become: true
  when: inventory_hostname == groups['managers'][0]

- name: Create directory for portainer config
  ansible.builtin.file:
    path: /etc/portainer
    state: directory
    mode: 0755
  become: true
  when: inventory_hostname == groups['managers'][0]

- name: Copy portainer docker compose yaml to swarm manager
  ansible.builtin.template:
    src: 'templates/compose-portainer.j2'
    dest: /etc/portainer/compose-portainer.yaml
    mode: 0644
  become: true
  when: inventory_hostname == groups['managers'][0]
