- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - net-tools
    state: present
  become: true

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' if ansible_architecture == 'aarch64' else ansible_architecture }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  become: true

- name: Install Docker Engine, containerd, and Docker Compose
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true

- name: Install Python Docker SDK via apt
  ansible.builtin.apt:
    name: python3-docker
    state: present
  become: true

- name: Ensure Docker service is running and enabled
  ansible.builtin.systemd_service:
    name: docker
    state: reloaded
    enabled: yes
  become: true

- name: Add current user to docker group (if needed for non-root access)
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes
  become: true
